-- require("presence"):setup({
-- buttons = false,
-- enable_line_number = false,
-- main_image = "file",
-- buttons = true,
-- neovim_image_text = "Neovim",
-- debounce_timeout = 10,
-- log_level = "debug",
-- workspace_text = "Working on my shitty code!",
-- })
--
-- require("presence").setup()
